apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamestash-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamestash
  template:
    metadata:
      labels:
        app: gamestash
    spec:
      containers:
        - name: gamestash-container
          image: gamestash:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gamestash-config
