name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.7.212.223 >> ~/.ssh/known_hosts

      - name: Deploy and restart Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.7.212.223 << 'EOF'
            cd ~/GameStash-server
            git pull origin main

            echo "Stopping old container (if any)..."
            docker stop gamestash-backend || true
            docker rm gamestash-backend || true

            echo "Building new Docker image..."
            docker build -t gamestash-backend .

            echo "Starting new container..."
            docker run -d \
              --name gamestash-backend \
              --env-file .env \
              -p 3000:3000 \
              --restart unless-stopped \
              gamestash-backend
          EOF
